services:
  postgres:
    image: postgres:17-alpine

    ports:
      - "${POSTGRES_PORT}:5432"

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  db-init:
    build:
      context: ./backend

    environment:
      DATABASE_URL: ${DATABASE_URL}

    depends_on:
      postgres:
        condition: service_healthy

    command: ["sh", "./scripts/db-init.sh"]
    restart: "no"

  backend:
    build:
      context: ./backend

    ports:
      - "${BACK_PORT}:${BACK_PORT}"

    environment:
      BACK_PORT: ${BACK_PORT}
      DATABASE_URL: ${DATABASE_URL}
      FRONTEND_URL: ${FRONTEND_URL}

      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      ACCESS_TOKEN_EXPIRES_IN: ${ACCESS_TOKEN_EXPIRES_IN}
      REFRESH_TOKEN_EXPIRES_IN: ${REFRESH_TOKEN_EXPIRES_IN}
      BCRYPT_ROUNDS: ${BCRYPT_ROUNDS}

      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}

    depends_on:
      db-init:
        condition: service_completed_successfully

  frontend:
    build:
      context: ./frontend

    ports:
      - "${FRONT_PORT}:${FRONT_PORT}"

    volumes:
      - ./frontend:/app
      - /app/node_modules

    environment:
      VITE_API_URL: ${VITE_API_URL}

    depends_on:
      backend:
        condition: service_started

volumes:
  postgres_data:
